export const imageMap: Record<string, string> = {
  "Slim Jim_Short_White": "/white cat.jpeg",
  "Slim Jim_Short_Tabby": "/cute cat.jpeg",
  "Slim Jim_Short_Calico": "/small calico.jpeg",
  "Slim Jim_Medium_White": "/white cat.jpeg",
  "Slim Jim_Medium_Tabby": "/images/slim_jim_medium_tabby.jpg",
  "Slim Jim_Medium_Calico": "/images/slim_jim_medium_calico.jpg",
  "Slim Jim_Long_White": "/images/slim_jim_long_white.jpg",
  "Slim Jim_Long_Tabby": "/images/slim_jim_long_tabby.jpg",
  "Slim Jim_Long_Calico": "/images/slim_jim_long_calico.jpg",

  Medium_Short_White: "/images/medium_short_white.jpg",
  Medium_Short_Tabby: "/images/medium_short_tabby.jpg",
  Medium_Short_Calico: "/images/medium_short_calico.jpg",
  Medium_Medium_White: "/images/medium_medium_white.jpg",
  Medium_Medium_Tabby: "/images/medium_medium_tabby.jpg",
  Medium_Medium_Calico: "/images/medium_medium_calico.jpg",
  Medium_Long_White: "/images/medium_long_white.jpg",
  Medium_Long_Tabby: "/images/medium_long_tabby.jpg",
  Medium_Long_Calico: "/images/medium_long_calico.jpg",

  Chonky_Short_White: "/images/chonky_short_white.jpg",
  Chonky_Short_Tabby: "/images/chonky_short_tabby.jpg",
  Chonky_Short_Calico: "/images/chonky_short_calico.jpg",
  Chonky_Medium_White: "/images/chonky_medium_white.jpg",
  Chonky_Medium_Tabby: "/images/chonky_medium_tabby.jpg",
  Chonky_Medium_Calico: "/images/chonky_medium_calico.jpg",
  Chonky_Long_White: "/images/chonky_long_white.jpg",
  Chonky_Long_Tabby: "/images/chonky_long_tabby.jpg",
  Chonky_Long_Calico: "/images/chonky_long_calico.jpg",
};
